project_name: authtranslator
release:
  github:
    owner: winhowes
    name: AuthTranslator
builds:
  - id: authtranslator
    main: ./app
    binary: authtranslator
    ldflags: -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - app/config.yaml
      - app/allowlist.yaml
