version: 2
project_name: authtranslator

release:
  overwrite: true
  github:
    owner: winhowes
    name: AuthTranslator

builds:
  - id: authtranslator
    main: ./app
    binary: authtranslator
    ldflags: -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - conf/config.yaml
      - conf/allowlist.yaml

dockers:
  - id: authtranslator_amd64
    goarch: amd64
    image_templates:
      - ghcr.io/winhowes/authtranslator:{{ .Tag }}-amd64
      - ghcr.io/winhowes/authtranslator:latest-amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64

  - id: authtranslator_arm64
    goarch: arm64
    image_templates:
      - ghcr.io/winhowes/authtranslator:{{ .Tag }}-arm64
      - ghcr.io/winhowes/authtranslator:latest-arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/winhowes/authtranslator:{{ .Tag }}
    image_templates:
      - ghcr.io/winhowes/authtranslator:{{ .Tag }}-amd64
      - ghcr.io/winhowes/authtranslator:{{ .Tag }}-arm64
  - name_template: ghcr.io/winhowes/authtranslator:latest
    image_templates:
      - ghcr.io/winhowes/authtranslator:latest-amd64
      - ghcr.io/winhowes/authtranslator:latest-arm64
