integrations:
  - name: slack
    destination: https://slack.com/
    in_rate_limit: 100
    out_rate_limit: 100
    rate_limit_window: 1m
    incoming_auth:
      - type: token
        params:
          secrets:
            - env:SLACK_TOKEN
          header: X-Auth
    outgoing_auth:
      - type: token
        params:
          secrets:
            - env:SLACK_TOKEN
          header: Authorization
          prefix: "Bearer "
