name: Docker Image

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ghcr.io/winhowes/authtranslator:$GITHUB_REF_NAME -t ghcr.io/winhowes/authtranslator:latest .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          docker push ghcr.io/winhowes/authtranslator:$GITHUB_REF_NAME
          docker push ghcr.io/winhowes/authtranslator:latest
