name: Go Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
      - name: Vet code
        run: go vet ./...
      - name: Lint (optional)
        run: |
          if command -v golangci-lint >/dev/null 2>&1; then
            golangci-lint run
          else
            echo "golangci-lint not installed, skipping"
          fi
      - name: Run tests
        run: go test ./...
