name: Go Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Export Go module cache path
        run: echo "GOMODCACHE=$(go env GOMODCACHE)" >> "$GITHUB_ENV"
      - name: Restore module cache
        id: modcache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.GOMODCACHE }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
      - name: Download dependencies
        run: go mod download
      - name: Vet code
        run: go vet ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.55.2
      - name: Check formatting
        run: test -z "$(gofmt -l .)"
      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Save module cache
        uses: actions/cache/save@v4
        if: ${{ steps.modcache.outputs.cache-hit != 'true' }}
        with:
          path: ${{ env.GOMODCACHE }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
